language: ruby

# Workaround for jruby-head build failure
before_install:
  - gem install bundler

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.2.0"
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
  - rbx
  - rbx-2
  - rbx-3
# Uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

matrix:
  allow_failures:
    # Rubinius is failing on Travis lately...
    - rvm: rbx
    - rvm: rbx-2
    - rvm: rbx-3

notifications:
  email: false
  irc:
    - "irc.rubircd.rocks#rubircd"
    - "irc.rubircd.rocks#sysadmininkudzu"
    - "chat.freenode.net#rubircd"
    - "irc.oftc.net#rubircd"
