language: ruby

# Workaround for jruby-head build failure
before_install:
  - gem install bundler
  - gem update bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
  - rbx
  - rbx-2
  - rbx-3
# Uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

matrix:
  # Rubinius is failing on Travis lately along with jruby-head...
  allow_failures:
    - rvm: rbx
    - rvm: rbx-2
    - rvm: rbx-3
    - rvm: jruby-head
  # Try JRuby with various Java implementations
  include:
    - rvm: jruby-19mode
      jdk: openjdk7
    - rvm: jruby-19mode
      jdk: openjdk8
    - rvm: jruby-19mode
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: jruby-head
      jdk: openjdk8
    - rvm: jruby-head
      jdk: oraclejdk8

notifications:
  email: false
  irc:
    - "irc.dilley.me#rubircd"
    - "irc.dilley.me#sysadmininkudzu"
    - "chat.freenode.net#rubircd"
    - "irc.oftc.net#rubircd"
